racker/salus-telemetry-envoy

Makefile
agents/command_handler_test.go
go.mod
go.sum
ingest/telegraf_json_test.go

Pegomock just added a new feature (https://github.com/petergtz/pegomock/issues/70) that allows for an "eventual" verification of mock calls. This eliminates the need to insert fixed delays to allow sufficient time/processing to elapse. The fixed delays would have create either brittle tests or extraneous time spent in the unit tests.
FYI, used `go get -u github.com/petergtz/pegomock` and it took care of `go.mod` and `go.sum` updates. I also had to use `go install github.com/petergtz/pegomock/...` to pick up the change to the code generator tool.

Use pegomock's new VerifyWasCalledEventually to avoid fixed delays

---

README.md
ambassador/connection.go
ambassador/connection_test.go
config/config_keys.go
telemetry_edge/telemetry-edge.proto

https://jira.rax.io/browse/SALUS-21
Allows the envoy to provide a field for which it can be uniquely identified.
If the envoy has a label with key matching the identifier then that value is valid.  The identifier defaults to `hostname`, which all envoys should be able to retrieve.
This value can also be overridden in the envoy config, like so
```
identifier: thisisatest
tls:
provided:
ca: certs/out/ca.pem
cert: certs/out/tenantA.pem
key: certs/out/tenantA-key.pem
ambassador:
address: localhost:6565
lumberjack:
bind: localhost:5044
labels:
thisisatest: valuegoeshere
```
Note that there is a custom label with a key that matches the identifier.  As the identifier is not an auto-generated value, the envoy would throw an error if this was not specified in the config.  Any label can be used, …

Add identifier property to connection config

---

config/bios.go
config/labels.go
config/serial.go
config/xen.go

This again wasn't complicated, but more a lesson in go/powershell.
It adds bios and serial number information to the default list of labels.
```
Windows:
←[37mDEBU←[0m[0003] discovered labels                             ←[37mlabels←[0
m="map[serial:99deec4d-db66-ab77-b6e6-86d392107627 bios-vendor:xen bios-version:
4.1.5 os:windows arch:amd64 hostname:jjbuchan-envoy- xen-id:instance-d406d728-fc
04-4f71-9a25-11b3b1d3a3fb]"
Linux:
DEBU[0000] discovered labels                             labels="map[bios-vendor:Xen bios-version:4.1.5 bios-date:11/28/2013 os:linux arch:amd64 hostname:jjbuchan-envoy-ubuntu1804 xen-id:instance-d92e7ca4-d82a-4fe7-a248-bd4a22a58c46 serial:1b9a4b69-f267-9512-b9b6-118528a1b214]"
```
* If 32bit is ever required, some additions will be needed.
* I started adding the …

Add bios and serial data to discovered labels

---

Makefile
ambassador/connection.go
ambassador/connection_test.go
telemetry_edge/telemetry-edge.proto

Discovered during review of #20 
Rather than pass the envoy's instance ID in the body of each gRPC call this change prepares for the removal of that field to instead convey the ID via a gRPC (HTTP/2) header field.
Uses the approach described [here](https://stackoverflow.com/a/42121891/121324) to set the metadata into the grpc outgoing context, which is then wrapped and used for the actual grpc calls. Keep in mind that "wrapped" contexts retain the values and cancellation properties of the outer context.
`make test`
n/a
None but there will need to be a follow PR to remove the `envoyId`/`instanceId` field from the message bodies; however, we should do that after #20 .

Pass envoy ID in gRPC header

---

ambassador/connection.go

Found during SALUS-94
When the Ambassador presents a bad TLS/X509 cert, the lower level gRPC connection will quietly re-attempt the connection forever. Instead we need to wrap the connection in a timeout/deadline to ensure that connectivity issues are apparent and handled in our app layer.

Enforce a timeout on connection attempt to Ambassador

---

ambassador/connection.go

I noticed that during some builds, [like this one](https://circleci.com/gh/racker/salus-telemetry-envoy/101), the standard egress connection would get stuck in a loop around the retry section.
Add a check that the overall app context hasn't been closed before retrying the retry.
Using existing unit tests, such as `TestStandardEgressConnection_PostLogEvent`

Check for closed context before retrying Ambassador connections

---

config/labels.go
config/labels_test.go

Part of https://jira.rax.io/browse/SALUS-265
When we prefix the Envoy labels later in the system, we lose the ability to differentiate the labels that were configured in the Envoy's config file. Therefore we lose the ability to enforce that the user isn't attempting to overwrite a discovered label.
Added some helper functions to apply the namespace as a prefix and validate the user didn't declare a label also prefixed with ours.
Unit tests were updated and expanded.
There will be a resource management PR to not apply the namespace there https://github.com/racker/salus-telemetry-resource-management/blob/master/src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java#L259

Namespace and enforce discovered labels

---

.github/PULL_REQUEST_TEMPLATE.md
config/labels.go
config/labels_test.go

Part of https://jira.rax.io/browse/SALUS-313
While further testing templated label retrieval, it was discovered that dot-delimited labels will cause usability issues:
https://github.com/racker/salus-telemetry-monitor-management/pull/27/files#diff-2332b138120e6010ec20463e65fd4465R129
The change in this PR mirrors the change made in the model PR
https://github.com/racker/salus-telemetry-model/pull/46/files#diff-333ce0b9f272ecee04b2df955791dc32R43
Unit test updated

Change labels delimiter to underscore for template friendliness

---

README.md

I had previously done this in another close, but when running as part of the bundle it failed due to pegomock.  Running this before the `make install` fixed things.

Add init step to build instructions

---

README.md
agents/agents.go
agents/agents_router.go
agents/agents_router_test.go
agents/command_handler.go
agents/hooks_for_test.go
cmd/run.go
config/config_keys.go

https://jira.rax.io/browse/SALUS-439
Our config file docs were lacking some important information, there was inconsistency in `agents` and `agent` sections of the yaml, and there wasn't a command-line arg for the Envoy data path.
Declare some more shared constants for the agents config keys and change and fix the other things mentioned above.
Existing unit tests

Improve agents config and add more config file docs

---

config/labels.go

The validation constraint on resource labels requires that label keys contain only underscores, letters, and digits. This adjusts the discovered labels to match that rule.
Existing unit tests

Use underscore delimiter in discovered labels

---

cmd/root.go

Part of https://jira.rax.io/browse/SALUS-448
logrus logs to stderr by default and since we're not seeing any output when running envoy as a runit service, I'm suspecting it's because it only mentions redirecting stdout of the `run` managed service
http://manpages.ubuntu.com/manpages/bionic/en/man8/runsv.8.html
Manually verify logs as before, but to stdout.

Tell logrus to log to stdout instead of default stderr

---

agents/telegraf.go
cmd/run.go

https://jira.rax.io/browse/SALUS-463
`runit`'s stop/restart commands send a SIGTERM to the process, but Envoy was only intercepting SIGINT.
Also explicitly setting the flush interval just to be sure. It looks like it defaults to `interval`'s value, but didn't find documentation to confirm that.
Manually for signal handling.

Handle SIGTERM and explicitly set telegraf flush interval

---

.goreleaser.yml
agents/agents.go
agents/command_handler.go

https://jira.rax.io/browse/SALUS-462
https://github.com/racker/salus-telemetry-envoy/pull/43 was necessary, but not completely the right fix for the issue:
```
time="2019-06-26T20:36:08Z" level=warning msg="failed to start agent" agentType=TELEGRAF error="failed to start command: fork/exec CURRENT/bin/telegraf: text file busy"
```
Developing/testing on MacOS was masking the real issue where the extracted executable file wasn't being closed and Linux it didn't want to exec a file that is open for writing in another process.
Also made the goreleaser snapshot naming a little shorter, such as
```
• creating                  archive=dist/telemetry-envoy_SNAPSHOT-160f34d_Linux_x86_64.tar.gz
```
FYI, using `make snapshot` is handy for creating a cross-compile on Mac OS that can run on Linux.

Extracted agent exe file wasn't being closed before starting it

---

agents/agents.go
agents/agents_router.go
agents/filebeat.go
agents/telegraf.go
agents/telegraf_test.go

https://jira.rax.io/browse/SALUS-467
Telegraf provides an `internal` input plugin which provides self-monitoring metrics. That is a good one to auto-configure to provide some baseline data and liveness info about the telegraf agent even before the user has configured any monitors.
Since this changes (and simplifies) the "ready to run telegraf" condition, the logic has been tweaked to always ensure the main telegraf config file is written, the `config.d` directory is present, but does not need to contain any config files. The latter used to be a precondition since telegraf would error out if no input plugins were configured -- now we guarantee at least one input plugin is always configured.
I also changed the purge config logic slightly to ensure that a new main telegraf config file is …

Pre-configure telegraf's internal input plugin

---

agents/agents_router.go
agents/agents_router_test.go
ambassador/connection.go
ambassador/connection_test.go
cmd/run.go

https://jira.rax.io/browse/SALUS-470
At this point in the Envoy connection handling https://github.com/racker/salus-telemetry-envoy/blob/93da632d9f87850e60dcc31db6ffa68be23b09be/ambassador/connection.go#L135 I realized that it wasn't actually stopping agents or purging monitor configs. Starting with an empty state was always an assumption of each envoy connection/instance ID...but the connection loss wasn't actually fulfilling that assumption.
Before the fix, the following metrics ingestion errors show the telegraf agent was still running after connection loss to the Ambassador:
```
time="2019-07-02T07:58:13-05:00" level=warning msg=terminating error="failed to receive instruction: rpc error: code = Unavailable desc = transport is closing"
time="2019-07-02T07:58:13-05:00" level=warning …
```

Stop agents and purge config on detach

---

agents/command_handler.go
agents/hooks_for_test.go
agents/telegraf.go
agents/telegraf_test.go

https://jira.rax.io/browse/SALUS-435
Improve envoy security by using config webserver instead of local config files
run the unit tests
Note that this is only tested on telegraf 1.11, (not all the earlier versions of telegraf support web based config.)

replace envoy config files with a config webserver

---

cmd/root.go

While writing up a quickstart guide for team members to run Envoy I realized the viper config file setup code I wrote was fairly wrong. I have since learned more about viper :). These new changes match the paths and config file naming that we're using so far for our own chef deploys where the config file is located at `/etc/salus/telemetry-envoy.yaml`.

Cleanup viper config file locating

---

agents/command_handler.go

I noticed the envoy debug logs the entire command object used to kick off an agent like telegraf:
```
time="2019-07-10T12:58:46-05:00" level=debug msg="starting agent" agentType=TELEGRAF cmd="&{CURRENT/bin/telegraf [CURRENT/bin/telegraf --config http://localhost:50487/91849e8c-65cf-4b23-836f-434a907ce0f8] [PATH=/Users/geof0549/.sdkman/candidates/scala/current/bin:
```
but we should really not log the environment variables since the envoy now conveys the `INFLUX_TOKEN` there and the user might have other sensitive environment variables.
Just log the command line args.

Don't debug log agent's command environment variables

---

.goreleaser.yml

https://jira.rax.io/browse/SALUS-466
On Windows it's awkward to use tar.gz archives, but GoReleaser makes it easy to fix that.
Use override option described in https://goreleaser.com/customization/#Archive
Also fixing some deprecation warnings while I was in there:
```
• ARCHIVES
• DEPRECATED: `archive` should not be used anymore, check https://goreleaser.com/deprecations#archive for more info.
• LINUX PACKAGES WITH NFPM
• DEPRECATED: `nfpm` should not be used anymore, check https://goreleaser.com/deprecations#nfpm for more info.
```
```
make snapshot
```
and confirm zip archive for Windows:
```
ls dist/*.zip
```

Create zip archive releases for Windows

---

README.md

Now that we have release builds performed in GCB as of https://github.com/racker/salus-telemetry-envoy/pull/54 the README's section on creating releases needed to be updated accordingly.

docs: updated README to describe release process via GCB

---

agents/agents_router.go
agents/telegraf.go
telemetry_edge/telemetry-edge.pb.go

https://jira.rax.io/browse/SALUS-481
While verifying the Envoy aspect of monitor translation I noticed that during an agent upgrade, the old agent process wasn't being stopped.
Ensure the agent runner is stopped during any installation, especially an upgrade.
There were a couple of other tweaks while I was in here.
Existing unit tests
- https://github.com/racker/salus-telemetry-monitor-management/pull/90
- https://github.com/racker/salus-telemetry-ambassador/pull/63

Stop agent runner during agent install/upgrade

---

.goreleaser.yml
pkg/scripts/postinstall.sh
pkg/scripts/postremove.sh
pkg/scripts/preremove.sh

https://jira.rax.io/browse/SALUS-639
On Ubuntu 14.04 (and other non-systemd distro/releases), the `systemctl` command is not present and systemd service files should not even be installed.
Use [the same trick telegraf package scripts used](https://github.com/influxdata/telegraf/blob/d71c8ed3b984394990e19a21c55495f5a6c308a0/scripts/post-install.sh#L71) to detect if systemd is the init process (pid==1).
For now, non-systemd systems will not have any service files installed or started. In a later enhancement we could add support for upstart and/or System V style init.
Manually with two separate vagrant boxes, `ubuntu/trusty64` and `ubuntu/xenial64`, to confirm the behaviors on non-systemd and systemd enabled systems.

Detect systemd before performing service install and systemctl calls

---

README.md
cloudbuild.yaml
cmd/root.go
config/config_keys.go
ingest/perf_test_ingestor.go
ingest/perf_test_ingestor_test.go

https://jira.rax.io/browse/SALUS-675
Creates a perf test mode which allows the envoy to generate dummy metrics for performance testing.  Also includes a webserver that accepts rest calls to change the rate of metrics per minute and the size/(number of float values) in each metric sent.
A new "--perf-test-port=<port number>" command line option invokes perf test mode and starts the webserver on <port number> parameter.
That webserver creates a rest endpoint which allows the rate/size of the metrics to be changed.
The metrics generation is implemented with a standalone "ingestor", i.e. one that doesn't ingest but just generates metrics on its own with connecting to an external agent.
unit tests added

perf test ingestor

---

auth/auth_service.go

When repose (in front of auth-service) fails or auth-service itself gives a non-200 response, there are no further details logged in the Envoy about why it failed. For example:
```
time="2020-01-09T18:31:28Z" level=fatal msg="unable to setup ambassador connection" error="http request to auth service failed: 500 Internal Server Error"
```
Grab the response body and include that in the error that gets logged.
I temporarily changed my auth-service code to throw an IllegalArgumentException to confirm that the gory details got logged when pointing my envoy at my local auth-service.

Improved the logging of failed auth service request

---

agents/converters_test.go
agents/testdata/TestConvertJsonToToml_apache.json
agents/testdata/TestConvertJsonToToml_apache.toml

Adds a test for apache monitor conversion from json to toml.
This shows that the `null` fields in the config will be ignored when converting to toml.

Adds a test for Apache monitor conversion

---

README.md
agents/filebeat.go
agents/filebeat_test.go
agents/telegraf.go
agents/telegraf_test.go
cmd/detached.go
cmd/run.go
config/listeners.go
config/listeners_test.go
ingest/ingest.go
ingest/lumberjack.go
ingest/perf_test_ingestor.go
ingest/perf_test_ingestor_test.go
ingest/telegraf_json.go
ingest/telegraf_json_test.go

https://jira.rax.io/browse/SALUS-748 and prepares for new line protocol ingestor to be added for https://jira.rax.io/browse/SALUS-594
We found on some systems where logstash was running that the lumberjack binding would fail since the equivalent logstash plugin was already bound at the standard port. That made me realize that we should ensure a few variations of ingest config to be allowed:
- disabling an ingestor entirely by setting a blank bind address
- binding to "all interfaces" by specifying `0.0.0.0` as the ingestor bind address, yet converting to `127.0.0.1` when the agent runner is looking up what to use for agent configs
- binding to any available port by allowing a 0 or absent port value
All of this also gets ready for me to add a line protocol ingest type to be used in …

Allowed ingestors to be disabled and improved resolving of listener address of those

---

README.md
agents/telegraf.go
agents/telegraf_test.go
ambassador/detached_runner.go
cmd/testdata/instructions-telegraf-testmonitor.json

https://jira.rax.io/browse/SALUS-785
Tried recreating https://gist.github.com/jjbuchan/32d3de48dd4a8a4b493a6983a3f74c30 by adding support for detached test-monitor instructions and running that 10-20 times.
Added support for test-monitor instructions to the existing detached runner logic and just log the returned results. Note: control-C needs to be used still to stop the envoy since detached mode also needs to support ongoing monitor runs.
Since I couldn't recreate the reported problem, the best compromise I could find was to improve the error message prefixes since admittedly "Parse:" wasn't very helpful.
From the `dev` directory, ran envoy with the arguments `detached --data-path=data-telemetry-envoy-detached --instructions=../apps/envoy/cmd/testdata/instructions-telegraf-testmonitor.js …

Support detached test-monitor instructions

---

README.md
cmd/root.go
config/config_keys.go
ingest/perf_test_ingestor.go
ingest/perf_test_ingestor_test.go

part of:
https://jira.rax.io/projects/SALUS/issues/SALUS-820
Allows perf test mode to be configured from the config file in addition to the webservice.
Adds config file variables for perf test fields: metricsPerMinute, and floatsPerMetric
unit tests pass

fix perf test config

---

ambassador/connection.go

i was running into a race condition where sometimes metrics were being posted to an unattatched connection which was causing a nil pointer panic.

now checks that connection is attached before posting metrics/log events

---

agents/agents.go
agents/agents_router.go
agents/agents_router_test.go
agents/filebeat.go
agents/oracle.go
agents/pkgagent.go
agents/telegraf.go

https://jira.rax.io/browse/SALUS-800
The handling of the `CURRENT` symlink that points to the currently installed agent-version directory was a bit brittle.
Improved the logic check for symlink's existence and/or what target directory (version) an existing symlink is referencing. It only creates or removes/recreates the symlink when necessary.
The resulting diff looks a bit hard to read, so you may want to use the side-by-side mode or review the resulting`func (ar *StandardAgentsRouter) ProcessInstall` code. 
Added more unit testing to specifically ensure an agent installation that switches versions works properly.

Improved handling of CURRENT symlink during agent upgrades

---

README.md
ambassador/connection.go
ambassador/connection_dev.go
cmd/detached.go
cmd/stressconnections.go

Part of https://jira.rax.io/browse/SALUS-852
It would be good to profile the Ambassador locally with a controlled number of Envoy connections...and it would be nice to do that without starting a bunch of Envoy processes.
Added a command that simulates any number of Envoys by opening multiple connections with a resource ID each. (The new README section provides even more description.)
Start the Ambassador and other usual services and confirm the new command works with the existing `dev/envoy-config-provided.yml` config file.

Added stress-connections command

---

README.md
cmd/root.go

While helping with public poller-envoy deployments I realized that
1. zone wasn't documented
2. there wasn't yet the ability to pass the zone via command line or env (latter is preferred for kube deploys)
3. the other env var configurable properties weren't clearly documented

Added zone as a command-line/env configurable property

---

.goreleaser.yml

Part of https://jira.rax.io/browse/SALUS-852
Apparently as of goreleaser 0.132.0 the `name_template` field in nfpms became `file_name_template`
https://goreleaser.com/customization/#NFPM
Since we were using the same as the default, removed the "renamed" field.
Get the latest goreleaser with `brew upgrade goreleaser` and run `make snapshot`.

Removed old name_template from goreleaser nfpms config

---

.dockerignore
ambassador/connection.go
cmd/stressconnections.go
k8s-stressconn-deploy.yml
skaffold-stressconn.yaml

Part of https://jira.rax.io/browse/SALUS-852
I wanted to have a way to deploy a one-off, dev image of the Envoy with that "dev" build tag enabled. The Cloud Code IntelliJ plugin along with its use of skaffold ended up solving that pretty nicely since it
- does a local build, tagged by git revision and then by SHA
- manipulates the image reference in the deployment manifest
- runs the deploy
- grabs the output of all the replicas
- and undeploys when stopping
During one of the perf runs the number of metrics processed by ambassador was lower than expected. I realized in the process of that that the "dropped metrics" logs were only debug-level. I made them warning level and a little more informative since I was running the stress-connections mode of envoys without `--debug` enabled.
I'll …

Added ability to do dev image deploy of Envoy
